FROM alpine:3.24

RUN apk add --no-cache \
    nginx \
    openssl

COPY default.conf /etc/nginx/http.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir /etc/nginx/ssl \
    && openssl req -x509 -newkey rsa:4096 \
    -keyout /etc/nginx/ssl/key.pem \
    -out /etc/nginx/ssl/cert.pem \
    -sha256 -days 365 -nodes -subj '/CN=svan-hoo.42.fr' -batch

CMD ["nginx", "-g", "daemon off;"]
