server {
	listen		443			ssl	default_server;
	listen		[::]:443	ssl	default_server;
	server_name	svan-hoo.42.fr;

	root	/var/www/html;
	index	index.php index.html index.htm index.nginx-debian.html;

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ \.php$ {
		include			snippets/fastcgi-php.conf;
		fastcgi_pass	wp-php:9000;
	}

	location ~ /\.ht {
		deny all;
	}
}
