FLUSH PRIVILEGES;
CREATE USER '$(DB_USER)'@'%' IDENTIFIED BY '$(DB_USER_PASSWORD)';
GRANT ALL PRIVILEGES ON *.* TO '$(DB_USER)'@'%' WITH GRANT OPTION;
CREATE DATABASE '$(DB_NAME)';
USE '$(DB_NAME)';
FLUSH PRIVILEGES;
