services:
  mariadb:
    build: mariadb/
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file: ../.env

  wp-php:
    build: wordpress/
    container_name: wp-php
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - website:/var/www/html
    networks:
      - inception
    env_file: ../.env

  nginx:
    build: nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    depends_on:
      - wp-php
      - mariadb
    volumes:
      - website:/var/www/html
    networks:
      - inception

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/svan-hoo/data/wordpress_db
      o: bind
  website:
    driver: local
    driver_opts:
      type: none
      device: /home/svan-hoo/data/wordpress_web
      o: bind

networks:
  inception:
